// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCghcVqbBah2uPc8m4ItbhZ92VC9Z1Kj2U',
    appId: '1:162049326540:web:62cb95b9bc7e7a959cb169',
    messagingSenderId: '162049326540',
    projectId: 'mindline-c4b2e',
    authDomain: 'mindline-c4b2e.firebaseapp.com',
    storageBucket: 'mindline-c4b2e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQ4j4RN_5-fzh2GIQPcsI4jwsN_jKio10',
    appId: '1:162049326540:ios:276b5cd7b315d8329cb169',
    messagingSenderId: '162049326540',
    projectId: 'mindline-c4b2e',
    storageBucket: 'mindline-c4b2e.firebasestorage.app',
    iosBundleId: 'com.daelim.haruEmtionFront',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQ4j4RN_5-fzh2GIQPcsI4jwsN_jKio10',
    appId: '1:162049326540:ios:276b5cd7b315d8329cb169',
    messagingSenderId: '162049326540',
    projectId: 'mindline-c4b2e',
    storageBucket: 'mindline-c4b2e.firebasestorage.app',
    iosBundleId: 'com.daelim.haruEmtionFront',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCghcVqbBah2uPc8m4ItbhZ92VC9Z1Kj2U',
    appId: '1:162049326540:web:01377c0e471943109cb169',
    messagingSenderId: '162049326540',
    projectId: 'mindline-c4b2e',
    authDomain: 'mindline-c4b2e.firebaseapp.com',
    storageBucket: 'mindline-c4b2e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAO2xm-dgUH2tXUUgfUAT2seNZKdHTsxs0',
    appId: '1:162049326540:android:d94b6444813200749cb169',
    messagingSenderId: '162049326540',
    projectId: 'mindline-c4b2e',
    storageBucket: 'mindline-c4b2e.firebasestorage.app',
  );

}